version: '3'

services:
  postgres:
    build: .
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pwd
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_DB_FILE: /run/secrets/pg_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_pwd:/run/secrets/pg_pwd
      - ./pg_user:/run/secrets/pg_user
      - ./pg_db:/run/secrets/pg_db
      - ./postgresql.conf:/usr/share/postgresql/postgresql.conf.sample
      - ./init-permissions.sh:/docker-entrypoint-initdb.d/init-permissions.sh
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
